Build 1.03 (#184)
* Added build test phase to release script

* Added README-DEVEL

* Noted method signature caveats for parameterized types

* Updated POD template with repo rename

* Added note on Rule vs Role

* Added file-exists tests to use/can.t

* Added "package main" to script example

* Added autobox note to "whats enabled" section

* Updated abstracts for PODs

* Update POD-writer to assist coalescing

* Updated documentation

* Built release version 1.03

diff --git a/release b/release
--- a/release
+++ b/release
@@ -10,6 +10,12 @@ if ! git diff-index --quiet HEAD --; then
   echo "Uncommitted changes!" && exit 0;
 fi
 
+# Test fake build before release
+if ! dzil test; then
+  echo "Build test failed!" && exit 0;
+fi
+
+# Cleanup the mess
 dzil clean
 
 # Delete existing POD documents
